### ISSUE TITLE
Implement stack walking without AsyncGetCallTrace

### ISSUE THREAD

**Issue by apangin** [async-profiler/async-profiler#66]
There is a number of problems with `AsyncGetCallTrace` API.

- [x] It is not accurate: sometimes it can point to neighbour methods. See #51 and [JDK-8022893](https://bugs.openjdk.java.net/browse/JDK-8022893).
- [x] It incorrectly handles certain corner cases. See [JDK-8178287](https://bugs.openjdk.java.net/browse/JDK-8178287).
- [x] It fails to walk through VM frames in Oracle JDK 9. See #60.
- [x] It requires preloading of all jmethodIDs thus resulting in startup time overhead. See https://github.com/jvm-profiling-tools/async-profiler/issues/14#issuecomment-340433290.
- [ ] It does not distinguish between interpreted, compiled and inlined frames.
- [x] In rare cases it may crash JVM. See #73.
- [ ] `-XX:MaxJavaStackTraceDepth` unobviously affects collected stack traces. See #89.
- [ ] Unloaded methods appears in the profile as `jvmtiError 23`.
- [x] Cannot walk stack traces from methods compiled with Graal.

- [x] = has workaround in async-profiler

The idea is to implement Java stack walking on our own without relying on AGCT. Since the agent runs in the context of JVM, it can access VM structures, especially those exported through VMStructs. It should be possible to replicate stack walking logic of the VM inside async-profiler, though it might be challenging. The main risk is that differrent versions of JVM may have different stack layout, but VMStructs along with special handling of the known versions is likely to help.

**Comment by toaler** [comment]
Hi @apangin any thoughts on when the features required to close this issue would be delivered?  How potentially contributors help with the open work?

**Comment by apangin** [comment]
@toaler Not sure, but unlikely in the nearest release. Are you interested in some particular problem of AGCT?

**Comment by LuoXiaoyi** [comment]
I'd like to know when will the async-profiler support J9?

**Comment by apangin** [comment]
@LuoXiaoyi I'd like to know that as well ;) Pull requests are welcome!

**Comment by apangin** [comment]
I'm closing this issue as obsolete.
Further work on AsyncGetCallTrace replacement will be carried out in #795.
